import numpy as np
from .hw_discovery import is_jetson as is_jetson
from _typeshed import Incomplete
from edgeiq.bounding_box import BoundingBox as BoundingBox

nj: Incomplete

def translate(image: np.ndarray, x: int, y: int) -> np.ndarray: ...
def rotate(image: np.ndarray, angle: int) -> np.ndarray: ...
def resize(image: np.ndarray, width: int | None = None, height: int | None = None, keep_scale: bool = True, inter: int = ...) -> np.ndarray: ...
def convert_to_jpg(image: np.ndarray, jpg_quality: int) -> bytes: ...
def list_images(base_path: str, contains: str | None = None) -> list[str]: ...
def list_files(base_path: str, valid_exts: list[str], contains: str | None = None) -> list[str]: ...
def safe_hstack(frames: list[np.ndarray], pad: bool = False): ...
def safe_vstack(frames: list[np.ndarray], pad: bool = False): ...
def pad_to_aspect_ratio(image: np.ndarray, a_ratio: float) -> tuple[np.ndarray, int, int]: ...
def cutout_image(image: np.ndarray, box: BoundingBox) -> np.ndarray: ...
def blend_images(foreground_image: np.ndarray, background_image: np.ndarray, alpha: float) -> np.ndarray: ...
def overlay_image(foreground_image: np.ndarray, background_image: np.ndarray, foreground_mask: np.ndarray) -> np.ndarray: ...
def perform_histogram_equalization(image: np.ndarray, color_space: str = 'GS', adaptive: bool = False, clip_limit: float = 2.0, tile_grid_size: tuple[int, int] = (8, 8)) -> np.ndarray: ...
def perform_gamma_correction(image: np.ndarray, gamma_value: float = 0.8, color: bool = False) -> np.ndarray: ...
def draw_rounded_rectangle(image: np.ndarray, pt1: tuple[int, int], pt2: tuple[int, int], color: tuple[int, int, int], thickness: int, corner_radius: int) -> None: ...

HorizontalTextAlignment: Incomplete
VerticalTextAlignment: Incomplete
TextAlignment = tuple[HorizontalTextAlignment, VerticalTextAlignment]
default_text_alignment_vertical: VerticalTextAlignment
default_text_alignment_horizontal: HorizontalTextAlignment

def draw_text_with_background(image: np.ndarray, text: str, start_x: int, start_y: int, font_size: float, font_thickness: int, color: tuple[int, int, int], background_padding: int = 10, background_corner_radius: int = 0, text_alignment: TextAlignment = ('left', 'top'), **kwargs) -> tuple[np.ndarray, int, int]: ...
