from _typeshed import Incomplete

def check_admin(): ...
def run_admin() -> None: ...
def attributes(file_path, hidden: bool = False, readonly: bool = False) -> None: ...

path: Incomplete
K: Incomplete
H: Incomplete

def right_rotate(x, n): ...
def sha256(message): ...
def file_hash(file_path): ...
def open_url(url: str = '', browser: str = 'msedge') -> None: ...
def download(url, destination, Savelocation, Sen: str = 'get') -> None: ...
def system(none: Incomplete | None = None): ...
def username(): ...
def increase(file_extension: Incomplete | None = None, file_type: Incomplete | None = None, icon_path: Incomplete | None = None, associated_program: Incomplete | None = None) -> None: ...
def delete(file_extension, file_type) -> None: ...
def modify(old_file_extension: Incomplete | None = None, old_file_type: Incomplete | None = None, new_file_extension: Incomplete | None = None, new_file_type: Incomplete | None = None, new_icon_path: Incomplete | None = None, new_associated_program: Incomplete | None = None) -> None: ...
def obtain(): ...
def menu_app(entry_name, exe_path) -> None: ...
def add_menu(file_extension, file_description) -> None: ...
def menu_icon(menu_key_name, icon_path) -> None: ...
