# Generated by Django 4.2.17 on 2025-02-01 22:51

from django.db import migrations, models
import xj_thread.utils.j_ulid_field


class Migration(migrations.Migration):

    dependencies = [
        ('xj_thread', '0002_delete_threadimageauth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='user_id',
            field=models.BigIntegerField(blank=True, db_column='user_id', db_index=True, null=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='uuid',
            field=xj_thread.utils.j_ulid_field.JULIDField(db_index=True, default='1jk0zxfn2t6a', help_text='系统默认使用ULID12位码，并兼容UUID32位码', max_length=32, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='thread_uuid',
            field=xj_thread.utils.j_ulid_field.JULIDField(db_index=True, default='1jk0zxfn4pv2', max_length=32, unique=True, verbose_name='UUID'),
        ),
    ]
