# Generated by Django 5.1 on 2025-02-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='completed/')),
                ('video_length', models.IntegerField(blank=True, null=True)),
                ('start_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('total_chunks', models.IntegerField(blank=True, default=0, null=True)),
                ('uploaded_chunks', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('available_chunk_size', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chunks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chunk_upload.upload')),
            ],
        ),
    ]
