import numpy as np
from ..types import ObjectDetectionPostProcessBatchParams as ObjectDetectionPostProcessBatchParams, ObjectDetectionPostProcessParams as ObjectDetectionPostProcessParams, ObjectDetectionPreProcessBatchParams as ObjectDetectionPreProcessBatchParams, ObjectDetectionPreProcessParams as ObjectDetectionPreProcessParams
from ..utils import register_post_processing as register_post_processing, register_post_processing_batch as register_post_processing_batch, register_pre_processing as register_pre_processing, register_pre_processing_batch as register_pre_processing_batch
from edgeiq.bounding_box import BoundingBox as BoundingBox

def xywh2xyxy(x): ...
def compute_iou(box, boxes): ...
def nms(boxes, scores, iou_threshold): ...
def common_pre_process(input_img, size): ...
def yolox_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def yolox_pre_process_batch(params: ObjectDetectionPreProcessBatchParams) -> np.ndarray: ...
def yolox_pre_process_trt(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def yolox_pre_process_batch_trt(params: ObjectDetectionPreProcessBatchParams) -> np.ndarray: ...
def yolox_post_process(params: ObjectDetectionPostProcessParams): ...
def yolox_post_process_batch(params: ObjectDetectionPostProcessBatchParams): ...
