import numpy as np
from ..types import ObjectDetectionPostProcessParams as ObjectDetectionPostProcessParams, ObjectDetectionPreProcessParams as ObjectDetectionPreProcessParams
from ..utils import register_post_processing as register_post_processing, register_pre_processing as register_pre_processing

def yolov4_onnx_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def yolov4_onnx_pre_process_trt(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def nms_cpu(boxes, confs, nms_thresh: float = 0.5): ...
def yolov4_onnx_post_process(params: ObjectDetectionPostProcessParams): ...
