
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-03T17:44:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "23a5e6c5c94cee754c4684fd8dc7c888d8493f04",
 "version": "1.3.1-rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
