DEFAULT_PORT = 51500
DEFAULT_RETRY_TIMEOUT = 1
DEFAULT_RETRY_COUNT = 3

TARGET_TEMPERATURE_MIN = 35
TARGET_TEMPERATURE_MAX = 60
TARGET_TEMPERATURE_DEFAULT = 43

TARGET_HUMIDITY_MIN = 60
TARGET_HUMIDITY_MAX = 99
TARGET_HUMIDITY_DEFAULT = 95

POWER_TIMER_MAX = 60
SALT_BATH_TIMER_MAX = 60
SWEEP_TIMER_MAX = 8
FAN_TIMER_MAX = 60

KEEP_ALIVE = b"\x2b"
