import numpy as np
from edgeiq._constants import SupportedPurposes as SupportedPurposes
from edgeiq.engine_accelerator import Accelerator as Accelerator, Engine as Engine
from edgeiq.object_detection import ObjectDetection as ObjectDetection, ObjectDetectionResults as ObjectDetectionResults
from edgeiq.tools.image_manipulation import convert_to_jpg as convert_to_jpg
from typing import List

class ObjectDetectionHttpClient(ObjectDetection):
    def __init__(self, model_id: str, server_url: str) -> None: ...
    def load(self, engine: Engine = ..., accelerator: Accelerator = ...): ...
    def detect_objects(self, image: np.ndarray, confidence_level: float = ..., overlap_threshold: float = ...) -> ObjectDetectionResults: ...
    def detect_objects_batch(self, images: List[np.ndarray], confidence_level: float = ..., overlap_threshold: float = ...) -> List[ObjectDetectionResults]: ...
