# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.9.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProjectWithFeed(BaseModel):
    """
    ProjectWithFeed
    """ # noqa: E501
    project_id: StrictStr
    name: StrictStr
    project_emoji: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    last_feed_update: StrictInt
    owner_id: StrictStr
    status: Optional[StrictStr] = None
    total_post_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["project_id", "name", "project_emoji", "description", "last_feed_update", "owner_id", "status", "total_post_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectWithFeed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if project_emoji (nullable) is None
        # and model_fields_set contains the field
        if self.project_emoji is None and "project_emoji" in self.model_fields_set:
            _dict['project_emoji'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if total_post_count (nullable) is None
        # and model_fields_set contains the field
        if self.total_post_count is None and "total_post_count" in self.model_fields_set:
            _dict['total_post_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectWithFeed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "name": obj.get("name"),
            "project_emoji": obj.get("project_emoji"),
            "description": obj.get("description"),
            "last_feed_update": obj.get("last_feed_update"),
            "owner_id": obj.get("owner_id"),
            "status": obj.get("status"),
            "total_post_count": obj.get("total_post_count")
        })
        return _obj


