import multiprocessing
import numpy as np

__all__ = ['MjpgVideoWriter']

class MjpgVideoWriter:
    def __init__(self, queue_depth: int = 2, port: int = 5000, max_image_width: int = 640, max_image_height: int = 480, jpg_quality: int = 75, **kwargs) -> None: ...
    def start(self): ...
    def write_frame(self, frame: np.ndarray): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def __del__(self) -> None: ...

class _ServerProcess(multiprocessing.Process):
    def __init__(self, ipaddr: str, port: int, tx_queue, max_image_width, max_image_height, jpg_quality, error_queue, *args, **kwargs) -> None: ...
    def run(self) -> None: ...
