from . import boundary_conditions
from . import turbulence
from . import initialization
from . import spatial_discretization
from . import solution_controls
from . import physical_behavior
from .spatial_discretization_fluid_ import SpatialDiscretizationFluid
from .solution_controls_fluid_ import SolutionControlsFluid
from .initialization_fluid_ import InitializationFluid
from .adjoint_controls_fluid_ import AdjointControlsFluid
from .physical_behavior_ import PhysicalBehavior
from .porous_behavior_ import PorousBehavior
from .turbulence_ import Turbulence
from .boundary_conditions_fluid_ import BoundaryConditionsFluid
from .basic_fluid_ import BasicFluid
