from typing import Any, List, ModuleType

class UserSettings:
    SETTINGS_MODULE: ModuleType = ...
    configured: bool = ...

    def __init__(self, dotted_path: str): ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...


class Settings:
    MODULE: ModuleType = ...
    _user_settings: UserSettings = ...

    def __init__(self) -> None: ...
    def __repr__(self): ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def get(self, name: str) -> Any: ...
    def keys(self) -> List[str]: ...


settings: Settings
