import numpy as np
from .runtime import Runtime as Runtime
from _typeshed import Incomplete
from edgeiq._utils import gen_logger as gen_logger

HAILORT_SUPPORTED_VERSIONS: Incomplete

class HailoRT(Runtime):
    def __init__(self, model_config) -> None: ...
    def load_engine(self): ...
    def activate_pipeline(self) -> None: ...
    def close_pipeline(self): ...
    configured_network: Incomplete
    activated_network: Incomplete
    def activate_network(self): ...
    def set_input(self, image: np.ndarray): ...
    input_data: Incomplete
    def forward(self): ...
    def deactivate_network(self, *args) -> None: ...
    def stop(self, *args) -> None: ...
