from .base_server import Server as Server
from .inference_thread import ObjectDetectionInferenceThread as ObjectDetectionInferenceThread
from .shared import Shared as Shared

class HttpInferenceServer:
    def __init__(self, host: str, port: int, purpose: str) -> None: ...
    def start(self) -> None: ...
    def close(self) -> None: ...
