from logging import Logger as base_logger
from typing import Literal

class Logger:
    instance: base_logger = ...

    def __init__(self, name: str = Literal['KRYPTONE']) -> None: ...

    @classmethod
    def create(cls, name: str) -> Logger: ...
    def warning(self, message: str, *args, **kwargs) -> None: ...
    def info(self, message: str, *args, **kwargs) -> None: ...
    def error(self, message: str, *args, **kwargs) -> None: ...
    def debug(self, message: str, *args, **kwargs) -> None: ...
    def critical(self, message: str, *args, **kwargs) -> None: ...


logger: Logger = ...


def setup() -> None: ...
