# coding: utf-8

"""
    Morphy Text Processing API

    API for compressing and expanding text content

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morphy_ti.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_compress_text(self) -> None:
        """Test case for compress_text

        Compress text to a specified percentage
        """
        pass

    def test_expand_text(self) -> None:
        """Test case for expand_text

        Expand text to a specified percentage
        """
        pass


if __name__ == '__main__':
    unittest.main()
