# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.9.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_ti.models.command import Command

class TestCommand(unittest.TestCase):
    """Command unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Command:
        """Test Command
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Command`
        """
        model = Command()
        if include_optional:
            return Command(
                command_id = '',
                account_id = '',
                name = '',
                description = '',
                parameters = [
                    ephor_ti.models.command_parameter.CommandParameter(
                        name = '', 
                        description = '', 
                        type = '', 
                        required = True, 
                        default = '', )
                    ],
                category = '',
                editable = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                steps = {
                    'key' : ephor_ti.models.command_step.CommandStep(
                        step_id = '', 
                        action = '', 
                        parameters = ephor_ti.models.parameters.Parameters(), 
                        next_step = '', 
                        condition = ephor_ti.models.condition.condition(), )
                    },
                is_system = True,
                is_prompt_only = True
            )
        else:
            return Command(
                command_id = '',
                account_id = '',
                name = '',
                description = '',
                parameters = [
                    ephor_ti.models.command_parameter.CommandParameter(
                        name = '', 
                        description = '', 
                        type = '', 
                        required = True, 
                        default = '', )
                    ],
        )
        """

    def testCommand(self):
        """Test Command"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
