# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.9.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_ti.api.background_services_api import BackgroundServicesApi


class TestBackgroundServicesApi(unittest.TestCase):
    """BackgroundServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackgroundServicesApi()

    def tearDown(self) -> None:
        pass

    def test_refresh_folder_api_v1_background_services_refresh_folder_post(self) -> None:
        """Test case for refresh_folder_api_v1_background_services_refresh_folder_post

        Refresh Folder
        """
        pass


if __name__ == '__main__':
    unittest.main()
