# Generated by Django 2.2 on 2021-08-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_message_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Limit to Group'),
        ),
    ]
