import numpy as np
from ..types import ObjectDetectionPostProcessParams as ObjectDetectionPostProcessParams, ObjectDetectionPreProcessParams as ObjectDetectionPreProcessParams
from ..utils import register_post_processing as register_post_processing, register_pre_processing as register_pre_processing
from edgeiq.bounding_box import BoundingBox as BoundingBox

def softmax(x): ...
def normalize_image(image, mean, std): ...
def box_cxcywh_to_xyxy(x): ...
def rescale_bboxes(out_bbox, size): ...
def detr_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def detr_pre_process_trt(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def detr_post_process(params: ObjectDetectionPostProcessParams): ...
