import numpy as np
from ..types import ObjectDetectionPostProcessBatchParams as ObjectDetectionPostProcessBatchParams, ObjectDetectionPostProcessParams as ObjectDetectionPostProcessParams, ObjectDetectionPreProcessBatchParams as ObjectDetectionPreProcessBatchParams, ObjectDetectionPreProcessParams as ObjectDetectionPreProcessParams
from ..utils import register_post_processing as register_post_processing, register_post_processing_batch as register_post_processing_batch, register_pre_processing as register_pre_processing, register_pre_processing_batch as register_pre_processing_batch
from edgeiq.bounding_box import BoundingBox as BoundingBox

def sigmoid(x): ...
def yolo_to_xyxy(boxes): ...
def common_pre_process(input_img, size): ...
def rt_detr_onnx_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def rt_detr_onnx_pre_process_batch(params: ObjectDetectionPreProcessBatchParams) -> np.ndarray: ...
def trt_rt_detr_onnx_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def trt_rt_detr_onnx_pre_process_batch(params: ObjectDetectionPreProcessBatchParams) -> np.ndarray: ...
def rt_detr_onnx_post_process(params: ObjectDetectionPostProcessParams): ...
def rt_detr_onnx_post_process_batch(params: ObjectDetectionPostProcessBatchParams): ...
