
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-05T14:11:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f290e7b30c70101012e4661ce9575e9cc6b48c51",
 "version": "4.0.0a11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
