
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-06T13:39:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d533d864c83a171cf095633067046a41d237893c",
 "version": "4.0.0a13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
