# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetServerlessEventrouterBusResult',
    'AwaitableGetServerlessEventrouterBusResult',
    'get_serverless_eventrouter_bus',
    'get_serverless_eventrouter_bus_output',
]

@pulumi.output_type
class GetServerlessEventrouterBusResult:
    """
    A collection of values returned by getServerlessEventrouterBus.
    """
    def __init__(__self__, bus_id=None, cloud_id=None, created_at=None, deletion_protection=None, description=None, folder_id=None, id=None, labels=None, name=None):
        if bus_id and not isinstance(bus_id, str):
            raise TypeError("Expected argument 'bus_id' to be a str")
        pulumi.set(__self__, "bus_id", bus_id)
        if cloud_id and not isinstance(cloud_id, str):
            raise TypeError("Expected argument 'cloud_id' to be a str")
        pulumi.set(__self__, "cloud_id", cloud_id)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if deletion_protection and not isinstance(deletion_protection, bool):
            raise TypeError("Expected argument 'deletion_protection' to be a bool")
        pulumi.set(__self__, "deletion_protection", deletion_protection)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if folder_id and not isinstance(folder_id, str):
            raise TypeError("Expected argument 'folder_id' to be a str")
        pulumi.set(__self__, "folder_id", folder_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter(name="busId")
    def bus_id(self) -> Optional[str]:
        return pulumi.get(self, "bus_id")

    @property
    @pulumi.getter(name="cloudId")
    def cloud_id(self) -> str:
        return pulumi.get(self, "cloud_id")

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> str:
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter(name="deletionProtection")
    def deletion_protection(self) -> bool:
        return pulumi.get(self, "deletion_protection")

    @property
    @pulumi.getter
    def description(self) -> str:
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> str:
        return pulumi.get(self, "folder_id")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def labels(self) -> Mapping[str, str]:
        return pulumi.get(self, "labels")

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        return pulumi.get(self, "name")


class AwaitableGetServerlessEventrouterBusResult(GetServerlessEventrouterBusResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetServerlessEventrouterBusResult(
            bus_id=self.bus_id,
            cloud_id=self.cloud_id,
            created_at=self.created_at,
            deletion_protection=self.deletion_protection,
            description=self.description,
            folder_id=self.folder_id,
            id=self.id,
            labels=self.labels,
            name=self.name)


def get_serverless_eventrouter_bus(bus_id: Optional[str] = None,
                                   name: Optional[str] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetServerlessEventrouterBusResult:
    """
    Get information about Serverless Event Router Bus.

    {{ .Description | trimspace }}

    {{- /* Uncomment this block as you add files with examples

    ## Example Usage

    {{ tffile "examples/serverless_eventrouter_bus/d_serverless_eventrouter_bus_1.tf" }}

    */ -}}

    {{ .SchemaMarkdown | trimspace }}
    """
    __args__ = dict()
    __args__['busId'] = bus_id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('yandex:index/getServerlessEventrouterBus:getServerlessEventrouterBus', __args__, opts=opts, typ=GetServerlessEventrouterBusResult).value

    return AwaitableGetServerlessEventrouterBusResult(
        bus_id=pulumi.get(__ret__, 'bus_id'),
        cloud_id=pulumi.get(__ret__, 'cloud_id'),
        created_at=pulumi.get(__ret__, 'created_at'),
        deletion_protection=pulumi.get(__ret__, 'deletion_protection'),
        description=pulumi.get(__ret__, 'description'),
        folder_id=pulumi.get(__ret__, 'folder_id'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        name=pulumi.get(__ret__, 'name'))
def get_serverless_eventrouter_bus_output(bus_id: Optional[pulumi.Input[Optional[str]]] = None,
                                          name: Optional[pulumi.Input[Optional[str]]] = None,
                                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetServerlessEventrouterBusResult]:
    """
    Get information about Serverless Event Router Bus.

    {{ .Description | trimspace }}

    {{- /* Uncomment this block as you add files with examples

    ## Example Usage

    {{ tffile "examples/serverless_eventrouter_bus/d_serverless_eventrouter_bus_1.tf" }}

    */ -}}

    {{ .SchemaMarkdown | trimspace }}
    """
    __args__ = dict()
    __args__['busId'] = bus_id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('yandex:index/getServerlessEventrouterBus:getServerlessEventrouterBus', __args__, opts=opts, typ=GetServerlessEventrouterBusResult)
    return __ret__.apply(lambda __response__: GetServerlessEventrouterBusResult(
        bus_id=pulumi.get(__response__, 'bus_id'),
        cloud_id=pulumi.get(__response__, 'cloud_id'),
        created_at=pulumi.get(__response__, 'created_at'),
        deletion_protection=pulumi.get(__response__, 'deletion_protection'),
        description=pulumi.get(__response__, 'description'),
        folder_id=pulumi.get(__response__, 'folder_id'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        name=pulumi.get(__response__, 'name')))
