
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-07T02:40:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d51a2f8efa074167380f6372d69ed0474fed5b3",
 "version": "2025.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
