import json
import setuptools

kwargs = json.loads(
    """
{
    "name": "cdktf-cdktf-provider-cloudflare",
    "version": "11.30.0",
    "description": "Prebuilt cloudflare Provider for Terraform CDK (cdktf)",
    "license": "MPL-2.0",
    "url": "https://github.com/cdktf/cdktf-provider-cloudflare.git",
    "long_description_content_type": "text/markdown",
    "author": "HashiCorp",
    "bdist_wheel": {
        "universal": true
    },
    "project_urls": {
        "Source": "https://github.com/cdktf/cdktf-provider-cloudflare.git"
    },
    "package_dir": {
        "": "src"
    },
    "packages": [
        "cdktf_cdktf_provider_cloudflare",
        "cdktf_cdktf_provider_cloudflare._jsii",
        "cdktf_cdktf_provider_cloudflare.access_application",
        "cdktf_cdktf_provider_cloudflare.access_ca_certificate",
        "cdktf_cdktf_provider_cloudflare.access_custom_page",
        "cdktf_cdktf_provider_cloudflare.access_group",
        "cdktf_cdktf_provider_cloudflare.access_identity_provider",
        "cdktf_cdktf_provider_cloudflare.access_keys_configuration",
        "cdktf_cdktf_provider_cloudflare.access_mutual_tls_certificate",
        "cdktf_cdktf_provider_cloudflare.access_mutual_tls_hostname_settings",
        "cdktf_cdktf_provider_cloudflare.access_organization",
        "cdktf_cdktf_provider_cloudflare.access_policy",
        "cdktf_cdktf_provider_cloudflare.access_rule",
        "cdktf_cdktf_provider_cloudflare.access_service_token",
        "cdktf_cdktf_provider_cloudflare.access_tag",
        "cdktf_cdktf_provider_cloudflare.account",
        "cdktf_cdktf_provider_cloudflare.account_member",
        "cdktf_cdktf_provider_cloudflare.address_map",
        "cdktf_cdktf_provider_cloudflare.api_shield",
        "cdktf_cdktf_provider_cloudflare.api_shield_operation",
        "cdktf_cdktf_provider_cloudflare.api_shield_operation_schema_validation_settings",
        "cdktf_cdktf_provider_cloudflare.api_shield_schema",
        "cdktf_cdktf_provider_cloudflare.api_shield_schema_validation_settings",
        "cdktf_cdktf_provider_cloudflare.api_token",
        "cdktf_cdktf_provider_cloudflare.argo",
        "cdktf_cdktf_provider_cloudflare.authenticated_origin_pulls",
        "cdktf_cdktf_provider_cloudflare.authenticated_origin_pulls_certificate",
        "cdktf_cdktf_provider_cloudflare.bot_management",
        "cdktf_cdktf_provider_cloudflare.byo_ip_prefix",
        "cdktf_cdktf_provider_cloudflare.certificate_pack",
        "cdktf_cdktf_provider_cloudflare.cloud_connector_rules",
        "cdktf_cdktf_provider_cloudflare.content_scanning",
        "cdktf_cdktf_provider_cloudflare.content_scanning_expression",
        "cdktf_cdktf_provider_cloudflare.custom_hostname",
        "cdktf_cdktf_provider_cloudflare.custom_hostname_fallback_origin",
        "cdktf_cdktf_provider_cloudflare.custom_pages",
        "cdktf_cdktf_provider_cloudflare.custom_ssl",
        "cdktf_cdktf_provider_cloudflare.d1_database",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_access_application",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_access_identity_provider",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_account_roles",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_accounts",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_api_token_permission_groups",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_dcv_delegation",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_device_posture_rules",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_devices",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_dlp_datasets",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_gateway_app_types",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_gateway_categories",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_infrastructure_access_targets",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_ip_ranges",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_list",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_lists",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_load_balancer_pools",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_origin_ca_certificate",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_origin_ca_root_certificate",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_record",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_rulesets",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_tunnel",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_tunnel_virtual_network",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_user",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zero_trust_access_application",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zero_trust_access_identity_provider",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zero_trust_infrastructure_access_targets",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zero_trust_tunnel_cloudflared",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zero_trust_tunnel_virtual_network",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zone",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zone_cache_reserve",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zone_dnssec",
        "cdktf_cdktf_provider_cloudflare.data_cloudflare_zones",
        "cdktf_cdktf_provider_cloudflare.device_dex_test",
        "cdktf_cdktf_provider_cloudflare.device_managed_networks",
        "cdktf_cdktf_provider_cloudflare.device_policy_certificates",
        "cdktf_cdktf_provider_cloudflare.device_posture_integration",
        "cdktf_cdktf_provider_cloudflare.device_posture_rule",
        "cdktf_cdktf_provider_cloudflare.device_settings_policy",
        "cdktf_cdktf_provider_cloudflare.dlp_profile",
        "cdktf_cdktf_provider_cloudflare.email_routing_address",
        "cdktf_cdktf_provider_cloudflare.email_routing_catch_all",
        "cdktf_cdktf_provider_cloudflare.email_routing_rule",
        "cdktf_cdktf_provider_cloudflare.email_routing_settings",
        "cdktf_cdktf_provider_cloudflare.fallback_domain",
        "cdktf_cdktf_provider_cloudflare.filter",
        "cdktf_cdktf_provider_cloudflare.firewall_rule",
        "cdktf_cdktf_provider_cloudflare.gre_tunnel",
        "cdktf_cdktf_provider_cloudflare.healthcheck",
        "cdktf_cdktf_provider_cloudflare.hostname_tls_setting",
        "cdktf_cdktf_provider_cloudflare.hostname_tls_setting_ciphers",
        "cdktf_cdktf_provider_cloudflare.hyperdrive_config",
        "cdktf_cdktf_provider_cloudflare.infrastructure_access_target",
        "cdktf_cdktf_provider_cloudflare.ipsec_tunnel",
        "cdktf_cdktf_provider_cloudflare.keyless_certificate",
        "cdktf_cdktf_provider_cloudflare.leaked_credential_check",
        "cdktf_cdktf_provider_cloudflare.leaked_credential_check_rule",
        "cdktf_cdktf_provider_cloudflare.list",
        "cdktf_cdktf_provider_cloudflare.list_item",
        "cdktf_cdktf_provider_cloudflare.load_balancer",
        "cdktf_cdktf_provider_cloudflare.load_balancer_monitor",
        "cdktf_cdktf_provider_cloudflare.load_balancer_pool",
        "cdktf_cdktf_provider_cloudflare.logpull_retention",
        "cdktf_cdktf_provider_cloudflare.logpush_job",
        "cdktf_cdktf_provider_cloudflare.logpush_ownership_challenge",
        "cdktf_cdktf_provider_cloudflare.magic_firewall_ruleset",
        "cdktf_cdktf_provider_cloudflare.magic_wan_gre_tunnel",
        "cdktf_cdktf_provider_cloudflare.magic_wan_ipsec_tunnel",
        "cdktf_cdktf_provider_cloudflare.magic_wan_static_route",
        "cdktf_cdktf_provider_cloudflare.managed_headers",
        "cdktf_cdktf_provider_cloudflare.mtls_certificate",
        "cdktf_cdktf_provider_cloudflare.notification_policy",
        "cdktf_cdktf_provider_cloudflare.notification_policy_webhooks",
        "cdktf_cdktf_provider_cloudflare.observatory_scheduled_test",
        "cdktf_cdktf_provider_cloudflare.origin_ca_certificate",
        "cdktf_cdktf_provider_cloudflare.page_rule",
        "cdktf_cdktf_provider_cloudflare.pages_domain",
        "cdktf_cdktf_provider_cloudflare.pages_project",
        "cdktf_cdktf_provider_cloudflare.provider",
        "cdktf_cdktf_provider_cloudflare.queue",
        "cdktf_cdktf_provider_cloudflare.r2_bucket",
        "cdktf_cdktf_provider_cloudflare.rate_limit",
        "cdktf_cdktf_provider_cloudflare.record",
        "cdktf_cdktf_provider_cloudflare.regional_hostname",
        "cdktf_cdktf_provider_cloudflare.regional_tiered_cache",
        "cdktf_cdktf_provider_cloudflare.risk_behavior",
        "cdktf_cdktf_provider_cloudflare.ruleset",
        "cdktf_cdktf_provider_cloudflare.snippet",
        "cdktf_cdktf_provider_cloudflare.snippet_rules",
        "cdktf_cdktf_provider_cloudflare.spectrum_application",
        "cdktf_cdktf_provider_cloudflare.split_tunnel",
        "cdktf_cdktf_provider_cloudflare.static_route",
        "cdktf_cdktf_provider_cloudflare.teams_account",
        "cdktf_cdktf_provider_cloudflare.teams_list",
        "cdktf_cdktf_provider_cloudflare.teams_location",
        "cdktf_cdktf_provider_cloudflare.teams_proxy_endpoint",
        "cdktf_cdktf_provider_cloudflare.teams_rule",
        "cdktf_cdktf_provider_cloudflare.tiered_cache",
        "cdktf_cdktf_provider_cloudflare.total_tls",
        "cdktf_cdktf_provider_cloudflare.tunnel",
        "cdktf_cdktf_provider_cloudflare.tunnel_config",
        "cdktf_cdktf_provider_cloudflare.tunnel_route",
        "cdktf_cdktf_provider_cloudflare.tunnel_virtual_network",
        "cdktf_cdktf_provider_cloudflare.turnstile_widget",
        "cdktf_cdktf_provider_cloudflare.url_normalization_settings",
        "cdktf_cdktf_provider_cloudflare.user_agent_blocking_rule",
        "cdktf_cdktf_provider_cloudflare.waiting_room",
        "cdktf_cdktf_provider_cloudflare.waiting_room_event",
        "cdktf_cdktf_provider_cloudflare.waiting_room_rules",
        "cdktf_cdktf_provider_cloudflare.waiting_room_settings",
        "cdktf_cdktf_provider_cloudflare.web_analytics_rule",
        "cdktf_cdktf_provider_cloudflare.web_analytics_site",
        "cdktf_cdktf_provider_cloudflare.web3_hostname",
        "cdktf_cdktf_provider_cloudflare.worker_cron_trigger",
        "cdktf_cdktf_provider_cloudflare.worker_domain",
        "cdktf_cdktf_provider_cloudflare.worker_route",
        "cdktf_cdktf_provider_cloudflare.worker_script",
        "cdktf_cdktf_provider_cloudflare.worker_secret",
        "cdktf_cdktf_provider_cloudflare.workers_cron_trigger",
        "cdktf_cdktf_provider_cloudflare.workers_domain",
        "cdktf_cdktf_provider_cloudflare.workers_for_platforms_dispatch_namespace",
        "cdktf_cdktf_provider_cloudflare.workers_for_platforms_namespace",
        "cdktf_cdktf_provider_cloudflare.workers_kv",
        "cdktf_cdktf_provider_cloudflare.workers_kv_namespace",
        "cdktf_cdktf_provider_cloudflare.workers_route",
        "cdktf_cdktf_provider_cloudflare.workers_script",
        "cdktf_cdktf_provider_cloudflare.workers_secret",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_application",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_custom_page",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_group",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_identity_provider",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_mtls_certificate",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_mtls_hostname_settings",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_organization",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_policy",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_service_token",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_short_lived_certificate",
        "cdktf_cdktf_provider_cloudflare.zero_trust_access_tag",
        "cdktf_cdktf_provider_cloudflare.zero_trust_device_certificates",
        "cdktf_cdktf_provider_cloudflare.zero_trust_device_managed_networks",
        "cdktf_cdktf_provider_cloudflare.zero_trust_device_posture_integration",
        "cdktf_cdktf_provider_cloudflare.zero_trust_device_posture_rule",
        "cdktf_cdktf_provider_cloudflare.zero_trust_device_profiles",
        "cdktf_cdktf_provider_cloudflare.zero_trust_dex_test",
        "cdktf_cdktf_provider_cloudflare.zero_trust_dlp_profile",
        "cdktf_cdktf_provider_cloudflare.zero_trust_dns_location",
        "cdktf_cdktf_provider_cloudflare.zero_trust_gateway_certificate",
        "cdktf_cdktf_provider_cloudflare.zero_trust_gateway_policy",
        "cdktf_cdktf_provider_cloudflare.zero_trust_gateway_proxy_endpoint",
        "cdktf_cdktf_provider_cloudflare.zero_trust_gateway_settings",
        "cdktf_cdktf_provider_cloudflare.zero_trust_infrastructure_access_target",
        "cdktf_cdktf_provider_cloudflare.zero_trust_key_access_key_configuration",
        "cdktf_cdktf_provider_cloudflare.zero_trust_list",
        "cdktf_cdktf_provider_cloudflare.zero_trust_local_fallback_domain",
        "cdktf_cdktf_provider_cloudflare.zero_trust_risk_behavior",
        "cdktf_cdktf_provider_cloudflare.zero_trust_risk_score_integration",
        "cdktf_cdktf_provider_cloudflare.zero_trust_split_tunnel",
        "cdktf_cdktf_provider_cloudflare.zero_trust_tunnel_cloudflared",
        "cdktf_cdktf_provider_cloudflare.zero_trust_tunnel_cloudflared_config",
        "cdktf_cdktf_provider_cloudflare.zero_trust_tunnel_route",
        "cdktf_cdktf_provider_cloudflare.zero_trust_tunnel_virtual_network",
        "cdktf_cdktf_provider_cloudflare.zone",
        "cdktf_cdktf_provider_cloudflare.zone_cache_reserve",
        "cdktf_cdktf_provider_cloudflare.zone_cache_variants",
        "cdktf_cdktf_provider_cloudflare.zone_dnssec",
        "cdktf_cdktf_provider_cloudflare.zone_hold",
        "cdktf_cdktf_provider_cloudflare.zone_lockdown",
        "cdktf_cdktf_provider_cloudflare.zone_settings_override"
    ],
    "package_data": {
        "cdktf_cdktf_provider_cloudflare._jsii": [
            "provider-cloudflare@11.30.0.jsii.tgz"
        ],
        "cdktf_cdktf_provider_cloudflare": [
            "py.typed"
        ]
    },
    "python_requires": "~=3.8",
    "install_requires": [
        "cdktf>=0.20.0, <0.21.0",
        "constructs>=10.3.0, <11.0.0",
        "jsii>=1.106.0, <2.0.0",
        "publication>=0.0.3",
        "typeguard>=2.13.3,<4.3.0"
    ],
    "classifiers": [
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: JavaScript",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Typing :: Typed",
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved"
    ],
    "scripts": []
}
"""
)

with open("README.md", encoding="utf8") as fp:
    kwargs["long_description"] = fp.read()


setuptools.setup(**kwargs)
