# Generated by Django 4.2.3 on 2023-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zb_logging', '0003_log_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='detail',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Log detail'),
        ),
    ]
