import multiprocessing.queues

class RtspVideoWriter:
    def __init__(self, port: int = ..., num_streams: int = ..., image_width: int = ..., image_height: int = ..., fps: int = ..., **kwargs) -> None: ...
    def start(self): ...
    def write_frame(self, frame, stream_idx: int = ...) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback) -> None: ...

class _SrcPipeline:
    def __init__(self, image_width, image_height, idx, fps, tx_queue, loop) -> None: ...
    @property
    def port(self): ...
    @property
    def mount(self): ...
    def start(self): ...
    def stop(self) -> None: ...

class _RtspServer:
    def __init__(self, port) -> None: ...
    def start(self): ...
    def add_stream(self, port, mount) -> None: ...

class _ServerProcess(multiprocessing.Process):
    def __init__(self, port, num_streams, tx_queues, image_width, image_height, fps, error_queue, *args, **kwargs) -> None: ...
    def run(self) -> None: ...
