# coding: utf-8

"""
    Social Toolkit

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from social_sdk_testing_ti.api.brand_api import BrandApi


class TestBrandApi(unittest.TestCase):
    """BrandApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrandApi()

    def tearDown(self) -> None:
        pass

    def test_tenant_tenant_id_brand_brand_id_compass_get(self) -> None:
        """Test case for tenant_tenant_id_brand_brand_id_compass_get

        Get the latest brand compass
        """
        pass

    def test_tenant_tenant_id_brand_brand_id_compass_trigger_post(self) -> None:
        """Test case for tenant_tenant_id_brand_brand_id_compass_trigger_post

        Trigger the generation of a brand compass
        """
        pass

    def test_tenant_tenant_id_brand_brand_id_delete(self) -> None:
        """Test case for tenant_tenant_id_brand_brand_id_delete

        Delete a brand
        """
        pass

    def test_tenant_tenant_id_brand_brand_id_get(self) -> None:
        """Test case for tenant_tenant_id_brand_brand_id_get

        Get brand details
        """
        pass

    def test_tenant_tenant_id_brand_brand_id_put(self) -> None:
        """Test case for tenant_tenant_id_brand_brand_id_put

        Update brand details
        """
        pass

    def test_tenant_tenant_id_brand_get(self) -> None:
        """Test case for tenant_tenant_id_brand_get

        List all active brands for a tenant
        """
        pass

    def test_tenant_tenant_id_brand_post(self) -> None:
        """Test case for tenant_tenant_id_brand_post

        Create a new brand for a tenant
        """
        pass


if __name__ == '__main__':
    unittest.main()
