import numpy as np
from .runtime import Runtime
from _typeshed import Incomplete
from edgeiq.model_config import ModelConfig

__all__ = ['OpenCV']

class OpenCV(Runtime):
    net: Incomplete
    layer_names: Incomplete
    def __init__(self, model_config: ModelConfig) -> None: ...
    def forward(self): ...
    def set_input(self, image: np.ndarray): ...
    def set_backend(self, backend) -> None: ...
    def set_accelerator(self, target) -> None: ...
    def set_layer_names(self) -> None: ...
