from _typeshed import Incomplete

def check_admin(): ...
def run_admin() -> None: ...

FILE_ATTRIBUTE_HIDDEN: int
FILE_ATTRIBUTE_READONLY: int
FILE_ATTRIBUTE_ARCHIVE: int
FILE_ATTRIBUTE_SYSTEM: int
FILE_ATTRIBUTE_COMPRESSED: int

def attributes(file_path, hidden: bool = False, readonly: bool = False, archive: bool = False, system: bool = False, compressed: bool = False) -> None: ...

path: Incomplete
K: Incomplete
H: Incomplete

def right_rotate(x, n): ...
def sha256(message): ...
def file_hash(file_path): ...
def open_url(url: str = '', browser: str = 'msedge') -> None: ...
def download(url, destination, Savelocation, Sen: str = 'get') -> None: ...
def system(none: Incomplete | None = None): ...
def username(): ...
def increase(file_extension: Incomplete | None = None, file_type: Incomplete | None = None, icon_path: Incomplete | None = None, associated_program: Incomplete | None = None) -> None: ...
def delete(file_extension, file_type) -> None: ...
def modify(old_file_extension: Incomplete | None = None, old_file_type: Incomplete | None = None, new_file_extension: Incomplete | None = None, new_file_type: Incomplete | None = None, new_icon_path: Incomplete | None = None, new_associated_program: Incomplete | None = None) -> None: ...
def obtain(): ...
def menu_app(entry_name, exe_path) -> None: ...
def add_menu(file_extension, file_description) -> None: ...
def menu_icon(menu_key_name, icon_path) -> None: ...
def variable(variable, value) -> None: ...
def Systemtime(wYear, wMonth, wDay, wHour, wMinute, wSecond, wMilliseconds) -> None: ...
def association(file_extension, program_path) -> None: ...
def systemkey(): ...
def way(): ...
def exvironment(): ...
def SystemTime(): ...
def read(file_extension, file_path): ...
def read_file(file_extension): ...
