class FPS:
    def __init__(self) -> None: ...
    def start(self): ...
    def stop(self): ...
    def update(self) -> None: ...
    def get_elapsed_seconds(self): ...
    def compute_fps(self): ...
