import threading
from edgeiq._utils import gen_logger as gen_logger
from edgeiq.tools.utils import empty_queue as empty_queue

class LoggerThread(threading.Thread):
    def __init__(self, log_queue) -> None: ...
    def run(self) -> None: ...
    def close(self) -> None: ...
