
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2025-01-31T16:54:53-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "df43e68c147c36fd760a589d6223ddc35fb27cbe",
 "version": "2.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
