import numpy as np
from .types import ObjectDetectionPostProcessParams, ObjectDetectionPreProcessParams

def dnn_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def ssd_post_process(params: ObjectDetectionPostProcessParams): ...
def ssd_flat_post_process(results: np.ndarray, image: np.ndarray, confidence_level: float): ...
def yolo_post_process(params: ObjectDetectionPostProcessParams): ...
