import numpy as np
from .types import ObjectDetectionPostProcessBatchParams as ObjectDetectionPostProcessBatchParams, ObjectDetectionPostProcessParams as ObjectDetectionPostProcessParams, ObjectDetectionPreProcessBatchParams as ObjectDetectionPreProcessBatchParams, ObjectDetectionPreProcessParams as ObjectDetectionPreProcessParams
from .utils import register_post_processing as register_post_processing, register_post_processing_batch as register_post_processing_batch, register_pre_processing as register_pre_processing, register_pre_processing_batch as register_pre_processing_batch
from edgeiq.bounding_box import BoundingBox as BoundingBox

def trt_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def trt_ssd_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def trt_ssd_post_process(params: ObjectDetectionPostProcessParams): ...
def trt_yolo_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def trt_yolo_pre_process_batch(params: ObjectDetectionPreProcessBatchParams) -> np.ndarray: ...
def process_nms_boxes(detections: np.ndarray, overlap_threshold: float): ...
def trt_yolo_post_process(params: ObjectDetectionPostProcessParams): ...
def trt_yolo_post_process_batch(params: ObjectDetectionPostProcessBatchParams): ...
