from _typeshed import Incomplete

def desktop(): ...
def system(none: Incomplete | None = None): ...
def getcwd(): ...
def montage(*paths): ...
def sdb(path, windows_disallowed: Incomplete | None = None, unix_disallowed: Incomplete | None = None): ...
