MAX_VARNAME_SEARCH_INDEX = 100

RESPONSE_SIGNAL_KEY = "__response__"
FEEDBACK_SIGNAL_KEY = "__feedback__"

MAX_LOOPS_PER_CYCLE_RANGE = [1, 7]
MAX_CYCLES_PER_PROMPT_RANGE = [10, 20]
MAX_PROMPTS_PER_LOOP_RANGE = [1, 3]
