from .output_gradation import OutputGradation
from .please_input_brightness import PleaseInputBrightness
from .please_input_hue import PleaseInputHue
from .please_input_number_of_colors_you_want_to_create import PleaseInputNumberOfColorsYouWantToCreate
from .please_input_saturation import PleaseInputSaturation
