__all__ = ['find_usb_device', 'find_pcie_device', 'find_hailo', 'find_nvidia_gpu', 'is_jetson', 'is_jetson_xavier_nx', 'is_jetson_agx_xavier', 'is_jetson_agx_orin', 'is_jetson_orin_nx', 'is_opencv_cuda_available', 'get_gpu_archs']

def find_usb_device(id_vendor: int, id_product: int) -> bool: ...
def find_pcie_device(id_vendor: str, id_product: str) -> bool: ...
def find_hailo() -> bool: ...
def find_nvidia_gpu() -> bool: ...
def is_jetson() -> bool: ...
def is_jetson_xavier_nx() -> bool: ...
def is_jetson_agx_xavier() -> bool: ...
def is_jetson_agx_orin() -> bool: ...
def is_jetson_orin_nx() -> bool: ...
def is_opencv_cuda_available() -> bool: ...
def get_gpu_archs(): ...
