
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-05T11:54:07-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a42c0ff8a764f5496d2d6d0672ba7ffecf2e49b2",
 "version": "2.54.1b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
