# Generated by Django 4.1.7 on 2023-03-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zb_logging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.CharField(max_length=250, verbose_name='Mail From')),
                ('mail_to', models.CharField(max_length=250, verbose_name='Mail To')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('smtp_code', models.IntegerField(default=0, verbose_name='SMTP Code')),
                ('smtp_error', models.CharField(max_length=250, null=True, verbose_name='SMTP Error')),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='zb_logging.log', verbose_name='Log')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
