# Generated by Django 4.2.9 on 2024-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zb_logging', '0005_alter_log_user_alter_maillog_smtp_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='The name of the model you would like to audit', max_length=250, verbose_name='Model Name')),
                ('on_create', models.BooleanField(default=False, help_text='If true, this entity will be audited on insert event', verbose_name='On Insert')),
                ('on_delete', models.BooleanField(default=False, help_text='If true, this entity will be audited on delete event', verbose_name='On Delete')),
                ('on_update', models.BooleanField(default=False, help_text='If true, this entity will be audited on update event', verbose_name='On Update')),
                ('enabled', models.BooleanField(default=True, help_text='If false, disable the audit rule', verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Audit Entity',
                'verbose_name_plural': 'Audit Entities',
                'ordering': ['model_name'],
                'unique_together': {('model_name',)},
            },
        ),
    ]
