# coding: utf-8

# flake8: noqa
"""
    Morphy Text Processing API

    API for compressing and expanding text content

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from morphy_ti.models.compress_text200_response import CompressText200Response
from morphy_ti.models.compress_text_request import CompressTextRequest
from morphy_ti.models.expand_text200_response import ExpandText200Response
from morphy_ti.models.expand_text_request import ExpandTextRequest
