
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-07T13:46:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "822d8bc4abfa218fbaa27ff7685cbf79ad0e852f",
 "version": "v3.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
