class QaicInferenceEngine:
    def __init__(self, binary, device_id, input_path, *args, **kwargs) -> None: ...
    def setup_qaic_resources(self) -> None: ...
    def run_inference(self): ...

class QaicRT:
    def __init__(self, model_config, device_id: int = ...) -> None: ...
    def set_input(self, image) -> None: ...
    def forward(self): ...
