
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-06T16:50:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d33f384833e94867159b45d3847b7e771bfd559c",
 "version": "1.6.2.post0.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
