from edgeiq._utils import JsonFile
from typing import List, Optional

class AppFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def analytics_cfg(self): ...
    @property
    def qa_images_cfg(self): ...
    @property
    def device_agent_connection_cfg(self): ...
    @property
    def model_id_list(self) -> List[str]: ...

class ProjectFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def project_id(self): ...

class AppConfig:
    def __init__(self) -> None: ...
    @property
    def model_id_list(self) -> List[str]: ...
    @property
    def analytics_cfg(self) -> Optional[dict]: ...
    @property
    def qa_images_cfg(self) -> Optional[dict]: ...
    @property
    def device_agent_connection_cfg(self) -> Optional[dict]: ...
    @property
    def project_id(self) -> str: ...
