class ConnectionError(Exception): ...
class PublishError(Exception): ...
class PacketSizeError(PublishError): ...
class PacketRateError(PublishError): ...
class ConnectionBlockedError(PublishError): ...
class NoMoreResults(Exception): ...
