class TimingProfiler:
    def __init__(self) -> None: ...
    @property
    def durations(self) -> list[dict]: ...
    def mark_start(self, tag: str): ...
    def mark(self, tag: str): ...
    def mark_end(self, tag: str): ...
    def generate_report(self) -> dict[str, dict[str, float]]: ...
