import numpy as np
from .processor import Processor
from edgeiq.model_config import ModelConfig
from typing import Tuple

class InstanceSegmentationProcessor(Processor):
    def __init__(self, model_config: ModelConfig) -> None: ...
    def load(self) -> None: ...
    def pre_process(self, image: np.ndarray): ...
    def post_process(self, results: Tuple[np.ndarray, np.ndarray], image: np.ndarray, confidence_level: float): ...
