class CacheError(Exception): ...


class ConfigurationError(Exception): ...


class EncryptionError(Exception): ...


class DecryptionError(Exception): ...


class APIError(Exception): ...
