
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-06T16:52:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9b81da2a2fe110cb4567f25d95e429e8e3cf517",
 "version": "1.6.2.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
