import numpy as np
from .types import ObjectDetectionPostProcessParams, ObjectDetectionPreProcessParams

def hailo_yolov3_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def hailo_yolov3_post_process(params: ObjectDetectionPostProcessParams): ...
def hailo_ssd_pre_process(params: ObjectDetectionPreProcessParams) -> np.ndarray: ...
def hailo_ssd_post_process(params: ObjectDetectionPostProcessParams): ...
