from .types import ObjectDetectionPostProcessBatchParams, ObjectDetectionPostProcessParams, ObjectDetectionPreProcessBatchParams, ObjectDetectionPreProcessParams

def qaic_yolo_pre_process(params: ObjectDetectionPreProcessParams): ...
def qaic_yolo_pre_process_batch(params: ObjectDetectionPreProcessBatchParams): ...
def qaic_yolo_post_process_batch(params: ObjectDetectionPostProcessBatchParams): ...
def qaic_yolo_post_process(params: ObjectDetectionPostProcessParams): ...
