def register_pre_processing(*combinations): ...
def register_post_processing(*combinations): ...
def register_pre_processing_batch(*combinations): ...
def register_post_processing_batch(*combinations): ...
