# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jackal_protobuf.canine_chain.notifications import query_pb2 as canine__chain_dot_notifications_dot_query__pb2
GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in canine_chain/notifications/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/canine_chain.notifications.Query/Params',
                request_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryParams.SerializeToString,
                response_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.Notification = channel.unary_unary(
                '/canine_chain.notifications.Query/Notification',
                request_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryNotification.SerializeToString,
                response_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryNotificationResponse.FromString,
                _registered_method=True)
        self.AllNotifications = channel.unary_unary(
                '/canine_chain.notifications.Query/AllNotifications',
                request_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotifications.SerializeToString,
                response_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsResponse.FromString,
                _registered_method=True)
        self.AllNotificationsByAddress = channel.unary_unary(
                '/canine_chain.notifications.Query/AllNotificationsByAddress',
                request_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsByAddress.SerializeToString,
                response_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsByAddressResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Params(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notification(self, request, context):
        """Queries a Notification object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllNotifications(self, request, context):
        """Queries a list of Notification items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllNotificationsByAddress(self, request, context):
        """Queries a list of Notification items by address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryParams.FromString,
                    response_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'Notification': grpc.unary_unary_rpc_method_handler(
                    servicer.Notification,
                    request_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryNotification.FromString,
                    response_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryNotificationResponse.SerializeToString,
            ),
            'AllNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.AllNotifications,
                    request_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotifications.FromString,
                    response_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsResponse.SerializeToString,
            ),
            'AllNotificationsByAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.AllNotificationsByAddress,
                    request_deserializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsByAddress.FromString,
                    response_serializer=canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsByAddressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'canine_chain.notifications.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('canine_chain.notifications.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.notifications.Query/Params',
            canine__chain_dot_notifications_dot_query__pb2.QueryParams.SerializeToString,
            canine__chain_dot_notifications_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Notification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.notifications.Query/Notification',
            canine__chain_dot_notifications_dot_query__pb2.QueryNotification.SerializeToString,
            canine__chain_dot_notifications_dot_query__pb2.QueryNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.notifications.Query/AllNotifications',
            canine__chain_dot_notifications_dot_query__pb2.QueryAllNotifications.SerializeToString,
            canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllNotificationsByAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.notifications.Query/AllNotificationsByAddress',
            canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsByAddress.SerializeToString,
            canine__chain_dot_notifications_dot_query__pb2.QueryAllNotificationsByAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
