# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jackal_protobuf.canine_chain.storage import query_pb2 as canine__chain_dot_storage_dot_query__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in canine_chain/storage/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/canine_chain.storage.Query/Params',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryParams.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.File = channel.unary_unary(
                '/canine_chain.storage.Query/File',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFile.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFileResponse.FromString,
                _registered_method=True)
        self.AllFiles = channel.unary_unary(
                '/canine_chain.storage.Query/AllFiles',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFiles.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesResponse.FromString,
                _registered_method=True)
        self.FilesFromNote = channel.unary_unary(
                '/canine_chain.storage.Query/FilesFromNote',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFilesFromNote.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFilesFromNoteResponse.FromString,
                _registered_method=True)
        self.OpenFiles = channel.unary_unary(
                '/canine_chain.storage.Query/OpenFiles',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryOpenFiles.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesResponse.FromString,
                _registered_method=True)
        self.AllFilesByMerkle = channel.unary_unary(
                '/canine_chain.storage.Query/AllFilesByMerkle',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByMerkle.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByMerkleResponse.FromString,
                _registered_method=True)
        self.AllFilesByOwner = channel.unary_unary(
                '/canine_chain.storage.Query/AllFilesByOwner',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByOwner.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByOwnerResponse.FromString,
                _registered_method=True)
        self.Proof = channel.unary_unary(
                '/canine_chain.storage.Query/Proof',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryProof.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryProofResponse.FromString,
                _registered_method=True)
        self.AllProofs = channel.unary_unary(
                '/canine_chain.storage.Query/AllProofs',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProofs.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProofsResponse.FromString,
                _registered_method=True)
        self.ProofsByAddress = channel.unary_unary(
                '/canine_chain.storage.Query/ProofsByAddress',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryProofsByAddress.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryProofsByAddressResponse.FromString,
                _registered_method=True)
        self.Provider = channel.unary_unary(
                '/canine_chain.storage.Query/Provider',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryProvider.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryProviderResponse.FromString,
                _registered_method=True)
        self.AllProviders = channel.unary_unary(
                '/canine_chain.storage.Query/AllProviders',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProviders.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProvidersResponse.FromString,
                _registered_method=True)
        self.Attestation = channel.unary_unary(
                '/canine_chain.storage.Query/Attestation',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAttestation.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAttestationResponse.FromString,
                _registered_method=True)
        self.AllAttestations = channel.unary_unary(
                '/canine_chain.storage.Query/AllAttestations',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllAttestations.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllAttestationsResponse.FromString,
                _registered_method=True)
        self.Report = channel.unary_unary(
                '/canine_chain.storage.Query/Report',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryReport.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryReportResponse.FromString,
                _registered_method=True)
        self.AllReports = channel.unary_unary(
                '/canine_chain.storage.Query/AllReports',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllReports.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllReportsResponse.FromString,
                _registered_method=True)
        self.FreeSpace = channel.unary_unary(
                '/canine_chain.storage.Query/FreeSpace',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFreeSpace.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFreeSpaceResponse.FromString,
                _registered_method=True)
        self.StoreCount = channel.unary_unary(
                '/canine_chain.storage.Query/StoreCount',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryStoreCount.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryStoreCountResponse.FromString,
                _registered_method=True)
        self.FindFile = channel.unary_unary(
                '/canine_chain.storage.Query/FindFile',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFindFile.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFindFileResponse.FromString,
                _registered_method=True)
        self.GetClientFreeSpace = channel.unary_unary(
                '/canine_chain.storage.Query/GetClientFreeSpace',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryClientFreeSpace.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryClientFreeSpaceResponse.FromString,
                _registered_method=True)
        self.GetPayData = channel.unary_unary(
                '/canine_chain.storage.Query/GetPayData',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryPayData.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryPayDataResponse.FromString,
                _registered_method=True)
        self.StoragePaymentInfo = channel.unary_unary(
                '/canine_chain.storage.Query/StoragePaymentInfo',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryStoragePaymentInfo.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryStoragePaymentInfoResponse.FromString,
                _registered_method=True)
        self.AllStoragePaymentInfo = channel.unary_unary(
                '/canine_chain.storage.Query/AllStoragePaymentInfo',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllStoragePaymentInfo.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllStoragePaymentInfoResponse.FromString,
                _registered_method=True)
        self.FileUploadCheck = channel.unary_unary(
                '/canine_chain.storage.Query/FileUploadCheck',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFileUploadCheck.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFileUploadCheckResponse.FromString,
                _registered_method=True)
        self.PriceCheck = channel.unary_unary(
                '/canine_chain.storage.Query/PriceCheck',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryPriceCheck.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryPriceCheckResponse.FromString,
                _registered_method=True)
        self.ActiveProviders = channel.unary_unary(
                '/canine_chain.storage.Query/ActiveProviders',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryActiveProviders.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryActiveProvidersResponse.FromString,
                _registered_method=True)
        self.StorageStats = channel.unary_unary(
                '/canine_chain.storage.Query/StorageStats',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryStorageStats.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryStorageStatsResponse.FromString,
                _registered_method=True)
        self.NetworkSize = channel.unary_unary(
                '/canine_chain.storage.Query/NetworkSize',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryNetworkSize.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryNetworkSizeResponse.FromString,
                _registered_method=True)
        self.AvailableSpace = channel.unary_unary(
                '/canine_chain.storage.Query/AvailableSpace',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAvailableSpace.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAvailableSpaceResponse.FromString,
                _registered_method=True)
        self.Gauges = channel.unary_unary(
                '/canine_chain.storage.Query/Gauges',
                request_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllGauges.SerializeToString,
                response_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllGaugesResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Params(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def File(self, request, context):
        """Queries a File by merkle, owner, and start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllFiles(self, request, context):
        """Queries a list of File items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FilesFromNote(self, request, context):
        """Queries a File by merkle, owner, and start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenFiles(self, request, context):
        """Queries a list of open files by provider_address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllFilesByMerkle(self, request, context):
        """Queries a list of File items matching the merkle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllFilesByOwner(self, request, context):
        """Queries a list of File items matching the owner.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Proof(self, request, context):
        """Queries a Proof by provider_address, merkle, owner, and start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllProofs(self, request, context):
        """Queries a list of Proof items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProofsByAddress(self, request, context):
        """Queries a list of Proof items by provider_address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Provider(self, request, context):
        """Queries a Provider by address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllProviders(self, request, context):
        """Queries a list of Provider items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attestation(self, request, context):
        """Queries an Attestation by prover, merkle, owner, and start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllAttestations(self, request, context):
        """Queries a list of Attestation items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Report(self, request, context):
        """Queries a Report by prover, merkle, owner, and start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllReports(self, request, context):
        """Queries a list of Report items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreeSpace(self, request, context):
        """Queries free space by address.
        TODO: how is this different from GetClientFreeSpace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreCount(self, request, context):
        """Queries how many files a provider has stored by address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindFile(self, request, context):
        """Queries where a file is located by merkle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientFreeSpace(self, request, context):
        """Queries free space by address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayData(self, request, context):
        """Queries a PayData by address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoragePaymentInfo(self, request, context):
        """Queries a StoragePaymentInfo by address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllStoragePaymentInfo(self, request, context):
        """Queries a list of StoragePaymentInfo items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUploadCheck(self, request, context):
        """Queries whether user can upload a file based on size.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PriceCheck(self, request, context):
        """Queries current price of storage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveProviders(self, request, context):
        """Queries a list of ActiveProviders items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageStats(self, request, context):
        """Queries protocol storage space used and purchased.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NetworkSize(self, request, context):
        """Queries how much storage space is being used on the network at this time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableSpace(self, request, context):
        """Queries the amount of offered storage by active providers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gauges(self, request, context):
        """Queries protocol storage space used and purchased.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryParams.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'File': grpc.unary_unary_rpc_method_handler(
                    servicer.File,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFile.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFileResponse.SerializeToString,
            ),
            'AllFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.AllFiles,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFiles.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesResponse.SerializeToString,
            ),
            'FilesFromNote': grpc.unary_unary_rpc_method_handler(
                    servicer.FilesFromNote,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFilesFromNote.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFilesFromNoteResponse.SerializeToString,
            ),
            'OpenFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenFiles,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryOpenFiles.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesResponse.SerializeToString,
            ),
            'AllFilesByMerkle': grpc.unary_unary_rpc_method_handler(
                    servicer.AllFilesByMerkle,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByMerkle.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByMerkleResponse.SerializeToString,
            ),
            'AllFilesByOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.AllFilesByOwner,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByOwner.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByOwnerResponse.SerializeToString,
            ),
            'Proof': grpc.unary_unary_rpc_method_handler(
                    servicer.Proof,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryProof.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryProofResponse.SerializeToString,
            ),
            'AllProofs': grpc.unary_unary_rpc_method_handler(
                    servicer.AllProofs,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProofs.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProofsResponse.SerializeToString,
            ),
            'ProofsByAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ProofsByAddress,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryProofsByAddress.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryProofsByAddressResponse.SerializeToString,
            ),
            'Provider': grpc.unary_unary_rpc_method_handler(
                    servicer.Provider,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryProvider.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryProviderResponse.SerializeToString,
            ),
            'AllProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.AllProviders,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProviders.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllProvidersResponse.SerializeToString,
            ),
            'Attestation': grpc.unary_unary_rpc_method_handler(
                    servicer.Attestation,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAttestation.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAttestationResponse.SerializeToString,
            ),
            'AllAttestations': grpc.unary_unary_rpc_method_handler(
                    servicer.AllAttestations,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllAttestations.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllAttestationsResponse.SerializeToString,
            ),
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryReport.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryReportResponse.SerializeToString,
            ),
            'AllReports': grpc.unary_unary_rpc_method_handler(
                    servicer.AllReports,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllReports.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllReportsResponse.SerializeToString,
            ),
            'FreeSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.FreeSpace,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFreeSpace.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFreeSpaceResponse.SerializeToString,
            ),
            'StoreCount': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreCount,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryStoreCount.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryStoreCountResponse.SerializeToString,
            ),
            'FindFile': grpc.unary_unary_rpc_method_handler(
                    servicer.FindFile,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFindFile.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFindFileResponse.SerializeToString,
            ),
            'GetClientFreeSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientFreeSpace,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryClientFreeSpace.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryClientFreeSpaceResponse.SerializeToString,
            ),
            'GetPayData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayData,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryPayData.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryPayDataResponse.SerializeToString,
            ),
            'StoragePaymentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.StoragePaymentInfo,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryStoragePaymentInfo.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryStoragePaymentInfoResponse.SerializeToString,
            ),
            'AllStoragePaymentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AllStoragePaymentInfo,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllStoragePaymentInfo.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllStoragePaymentInfoResponse.SerializeToString,
            ),
            'FileUploadCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.FileUploadCheck,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryFileUploadCheck.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryFileUploadCheckResponse.SerializeToString,
            ),
            'PriceCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceCheck,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryPriceCheck.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryPriceCheckResponse.SerializeToString,
            ),
            'ActiveProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveProviders,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryActiveProviders.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryActiveProvidersResponse.SerializeToString,
            ),
            'StorageStats': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageStats,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryStorageStats.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryStorageStatsResponse.SerializeToString,
            ),
            'NetworkSize': grpc.unary_unary_rpc_method_handler(
                    servicer.NetworkSize,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryNetworkSize.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryNetworkSizeResponse.SerializeToString,
            ),
            'AvailableSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableSpace,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAvailableSpace.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAvailableSpaceResponse.SerializeToString,
            ),
            'Gauges': grpc.unary_unary_rpc_method_handler(
                    servicer.Gauges,
                    request_deserializer=canine__chain_dot_storage_dot_query__pb2.QueryAllGauges.FromString,
                    response_serializer=canine__chain_dot_storage_dot_query__pb2.QueryAllGaugesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'canine_chain.storage.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('canine_chain.storage.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/Params',
            canine__chain_dot_storage_dot_query__pb2.QueryParams.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def File(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/File',
            canine__chain_dot_storage_dot_query__pb2.QueryFile.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllFiles',
            canine__chain_dot_storage_dot_query__pb2.QueryAllFiles.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FilesFromNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/FilesFromNote',
            canine__chain_dot_storage_dot_query__pb2.QueryFilesFromNote.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryFilesFromNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/OpenFiles',
            canine__chain_dot_storage_dot_query__pb2.QueryOpenFiles.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllFilesByMerkle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllFilesByMerkle',
            canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByMerkle.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByMerkleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllFilesByOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllFilesByOwner',
            canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByOwner.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllFilesByOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Proof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/Proof',
            canine__chain_dot_storage_dot_query__pb2.QueryProof.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllProofs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllProofs',
            canine__chain_dot_storage_dot_query__pb2.QueryAllProofs.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllProofsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProofsByAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/ProofsByAddress',
            canine__chain_dot_storage_dot_query__pb2.QueryProofsByAddress.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryProofsByAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Provider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/Provider',
            canine__chain_dot_storage_dot_query__pb2.QueryProvider.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllProviders',
            canine__chain_dot_storage_dot_query__pb2.QueryAllProviders.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attestation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/Attestation',
            canine__chain_dot_storage_dot_query__pb2.QueryAttestation.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAttestationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllAttestations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllAttestations',
            canine__chain_dot_storage_dot_query__pb2.QueryAllAttestations.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllAttestationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/Report',
            canine__chain_dot_storage_dot_query__pb2.QueryReport.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllReports',
            canine__chain_dot_storage_dot_query__pb2.QueryAllReports.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreeSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/FreeSpace',
            canine__chain_dot_storage_dot_query__pb2.QueryFreeSpace.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryFreeSpaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/StoreCount',
            canine__chain_dot_storage_dot_query__pb2.QueryStoreCount.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryStoreCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/FindFile',
            canine__chain_dot_storage_dot_query__pb2.QueryFindFile.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryFindFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientFreeSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/GetClientFreeSpace',
            canine__chain_dot_storage_dot_query__pb2.QueryClientFreeSpace.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryClientFreeSpaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/GetPayData',
            canine__chain_dot_storage_dot_query__pb2.QueryPayData.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryPayDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoragePaymentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/StoragePaymentInfo',
            canine__chain_dot_storage_dot_query__pb2.QueryStoragePaymentInfo.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryStoragePaymentInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllStoragePaymentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AllStoragePaymentInfo',
            canine__chain_dot_storage_dot_query__pb2.QueryAllStoragePaymentInfo.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllStoragePaymentInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileUploadCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/FileUploadCheck',
            canine__chain_dot_storage_dot_query__pb2.QueryFileUploadCheck.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryFileUploadCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PriceCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/PriceCheck',
            canine__chain_dot_storage_dot_query__pb2.QueryPriceCheck.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryPriceCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActiveProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/ActiveProviders',
            canine__chain_dot_storage_dot_query__pb2.QueryActiveProviders.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryActiveProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StorageStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/StorageStats',
            canine__chain_dot_storage_dot_query__pb2.QueryStorageStats.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryStorageStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NetworkSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/NetworkSize',
            canine__chain_dot_storage_dot_query__pb2.QueryNetworkSize.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryNetworkSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AvailableSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/AvailableSpace',
            canine__chain_dot_storage_dot_query__pb2.QueryAvailableSpace.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAvailableSpaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Gauges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/canine_chain.storage.Query/Gauges',
            canine__chain_dot_storage_dot_query__pb2.QueryAllGauges.SerializeToString,
            canine__chain_dot_storage_dot_query__pb2.QueryAllGaugesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
