import multiprocessing.queues
import queue

class MultiprocessingCircularQueue(multiprocessing.queues.Queue):
    def __init__(self, *args, **kwargs) -> None: ...
    def put(self, obj) -> None: ...

def empty_queue(q: queue.Queue | multiprocessing.queues.Queue) -> None: ...
