import numpy as np
from .processor import Processor
from edgeiq.model_config import ModelConfig

class SemanticSegmentationProcessor(Processor):
    def __init__(self, model_config: ModelConfig) -> None: ...
    def load(self) -> None: ...
    def pre_process(self, image: np.ndarray): ...
    def post_process(self, results: np.ndarray, image: np.ndarray): ...
