from .shared import ErrorRsp as ErrorRsp, InferenceBatchCmd as InferenceBatchCmd, InferenceCmd as InferenceCmd, LoadModelCmd as LoadModelCmd, Rsp as Rsp, Shared as Shared
from _typeshed import Incomplete
from edgeiq.model_config.model_config import ModelConfig as ModelConfig
from edgeiq.object_detection import ObjectDetectionResults as ObjectDetectionResults
from edgeiq.tools.results_serialization import to_json_serializable as to_json_serializable

werkzeug_logger: Incomplete
LOGGER: Incomplete
app: Incomplete

def handle_error(error): ...
def model(): ...
def inference(): ...
def inference_batch(): ...

class Server:
    def __init__(self, shared: Shared, host: str, port: int) -> None: ...
    def start(self) -> None: ...
