"""Environment variables used in the sandbox."""

# ==== [ Environment variable names ] ====
CUSTOMER_REPO_ID = "CUSTOMER_REPO_ID"
FEATURE_FLAGS_BASE64 = "FEATURE_FLAGS_BASE64"
REPO_CONFIG_BASE64 = "REPO_CONFIG_BASE64"
LOWSIDE_TOKEN = "LOWSIDE_TOKEN"
HIGHSIDE_TOKEN = "HIGHSIDE_TOKEN"
IS_SANDBOX = "IS_SANDBOX"
