from at_common_models.stock.financials.base_models import BaseBalanceSheetStatementModel

class QuarterBalanceSheetStatementModel(BaseBalanceSheetStatementModel):
    __tablename__ = "stock_financials_quarter_balance_sheet_statements"