import argparse
from argparse import ArgumentParser, Namespace
from collections import OrderedDict

class BaseCommand:
    help_text: str = ...
    command_registry: OrderedDict = ...
    requires_system_checks: bool = ...

    def create_parser(self, **kwargs) -> argparse.ArgumentParser: ...
    def add_arguments(self, parser: ArgumentParser) -> None: ...
    def execute(self, namespace: Namespace = ...) -> None: ...


class ProjectCommand(BaseCommand):
    ...
