class SimpleCameraBlockageResults:
    def __init__(self, blocked_status, duration, std_dev, blocked_ratio) -> None: ...
    @property
    def blocked_status(self): ...
    @property
    def duration(self): ...
    @property
    def std_dev(self): ...
    @property
    def blocked_ratio(self): ...

def detect_simple_camera_blockage(image, blocked_threshold: float = 0.9, std_dev_threshold: float = 2.0, detect_quadrants: bool = True): ...
